# DESCRIPTOR GENERATION

In [1]:
from mlchem.chem.calculator import descriptors
from mlchem.chem.manipulation import create_molecule
from mlchem.helper import dfs_to_excel
import pandas as pd
import numpy as np
data = pd.read_csv('../data/data.csv')

### RDKit

In [2]:
desc_rdkit = descriptors.get_rdkitDesc(data.SMILES,include_3D=False)
desc_rdkit.drop_duplicates(inplace=True)
print(desc_rdkit.isna().sum().sum())

columns_to_keep = []
for c in desc_rdkit.columns:
    try:
        pd.to_numeric(desc_rdkit[c])
        columns_to_keep.append(c)
    except Exception:
        pass
desc_rdkit = desc_rdkit[columns_to_keep]

desc_rdkit.replace([np.inf, -np.inf], np.nan, inplace=True)
desc_rdkit.dropna(axis=1,inplace=True) # axis 0: rows, axis 1: columns

print(desc_rdkit.isna().sum().sum())


desc_rdkit.index.rename('SMILES',inplace=True)
desc_rdkit.to_csv('../data/data_rdkit.csv')
desc_rdkit

164
0

,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,HeavyAtomMolWt,ExactMolWt,NumValenceElectrons,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
SMILES,,,,,,,,,,,,,,,,,,,,,
CO,7.000000,7.000000,1.000000,1.000000,0.385284,3.000000,32.042,28.010,32.026215,14,...,0,0,0,0,0,0,0,0,0,0
C=NCCC(CCO)CCCCOC(=O)C=O,10.509995,10.509995,0.170950,-0.812254,0.192921,11.823529,243.303,222.135,243.147058,98,...,0,0,0,0,0,0,0,0,1,0
CCC=C=NC#CCC=NCCC(CCO)CCCCOC(=O)C=O,10.666806,10.666806,0.156018,-0.822758,0.138151,11.120000,348.443,320.219,348.204907,138,...,0,0,0,0,0,0,0,0,1,0
C#CCCCCOCCC=C=NC#CCC=NCCC(CCO)CCCCOC(=O)C=O,10.726874,10.726874,0.142995,-0.829415,0.082425,11.000000,444.572,408.284,444.262422,176,...,0,0,0,1,0,0,0,0,3,0
O=CC(=O)OCCCCC(CCO)CCN=CCC#CN=C=CCCOCCCCC1=CCCC=C1,10.757642,10.757642,0.147038,-0.825632,0.065004,13.305556,498.664,456.328,498.309372,198,...,0,0,0,0,0,0,0,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CCCC(C)CCC1=C(C)C=C1,2.362870,2.362870,0.906759,0.906759,0.573841,17.916667,164.292,144.132,164.156501,68,...,0,0,0,0,0,0,0,0,0,0
CCCSCC=CC(C)CN=O,9.861364,9.861364,0.296043,0.296043,0.348033,13.500000,187.308,170.172,187.103085,70,...,1,0,0,0,0,0,0,0,0,0
CCCCC=O,9.563750,9.563750,0.732639,0.732639,0.374279,8.166667,86.134,76.054,86.073165,36,...,0,0,0,0,0,0,0,0,2,0
CCCC=CCCC(C)CCCC=CCO,8.567336,8.567336,0.178350,0.178350,0.428363,13.937500,224.388,196.164,224.214016,94,...,0,0,0,0,0,0,0,0,2,0
CCC(C)CCCC=CC=CCOCCCC=O,10.047806,10.047806,0.597024,0.597024,0.293755,13.444444,252.398,224.174,252.208930,104,...,0,0,0,0,0,0,0,0,2,0

### Mordred

In [3]:
desc_mordred = descriptors.get_mordredDesc(data.SMILES)

##### Some descriptors returns an error, include only those descriptors that can be converted to numbers

In [4]:
columns_to_keep = []
for c in desc_mordred.columns:
    try:
        pd.to_numeric(desc_mordred[c])
        columns_to_keep.append(c)
    except Exception:
        pass
desc_mordred_filtered = desc_mordred[columns_to_keep]
desc_mordred_filtered

,ABC,ABCGG,nAcid,nBase,SpAbs_A,SpMax_A,SpDiam_A,SpAD_A,SpMAD_A,LogEE_A,...,SRW09,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb2
CO,0.000000,0.000000,0,0,2.000000,1.000000,2.000000,2.000000,1.000000,1.407606,...,0.0,1.098612,7.493061,32.026215,5.337702,1,0,2.0,1.0,1.000000
C=NCCC(CCO)CCCCOC(=O)C=O,11.423098,10.616217,0,0,20.568632,2.105876,4.211752,20.568632,1.209920,3.655991,...,0.0,8.641709,46.895533,243.147058,6.398607,682,17,66.0,67.0,4.416667
CCC=C=NC#CCC=NCCC(CCO)CCCCOC(=O)C=O,17.079953,13.760084,0,0,30.716449,2.112381,4.224761,30.716449,1.228658,4.042043,...,0.0,8.946245,56.684840,348.204907,6.569904,2234,25,98.0,99.0,6.416667
C#CCCCCOCCC=C=NC#CCC=NCCC(CCO)CCCCOC(=O)C=O,22.029700,15.964321,0,0,39.549181,2.112409,4.224818,39.549181,1.235912,4.289084,...,0.0,9.153029,64.851094,444.262422,6.533271,4887,32,126.0,127.0,8.166667
O=CC(=O)OCCCCC(CCO)CCN=CCC#CN=C=CCCOCCCCC1=CCCC=C1,25.565234,17.349631,0,0,45.485957,2.158465,4.316929,45.485957,1.263499,4.427755,...,0.0,9.497247,70.041100,498.309372,6.388582,6897,38,150.0,155.0,8.916667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CCCC(C)CCC1=C(C)C=C1,8.663621,8.403541,0,0,14.172260,2.296750,4.593500,14.172260,1.181022,3.383041,...,0.0,9.186560,42.557671,164.156501,5.129891,233,11,54.0,59.0,2.861111
CCCSCC=CC(C)CN=O,7.887564,7.646871,0,0,14.007413,2.031442,4.062884,14.007413,1.167284,3.298990,...,0.0,8.049746,39.532688,187.103085,6.451831,265,10,44.0,43.0,3.166667
CCCCC=O,3.535534,3.869735,0,0,6.987918,1.801938,3.603875,6.987918,1.164653,2.579830,...,0.0,6.608001,28.105124,86.073165,5.379573,35,3,18.0,16.0,1.750000
CCCC=CCCC(C)CCCC=CCO,10.715992,9.508853,0,0,19.181769,2.052881,4.105762,19.181769,1.198861,3.589159,...,0.0,8.331105,45.012208,224.214016,5.095773,631,14,60.0,59.0,4.166667
CCC(C)CCCC=CC=CCOCCCC=O,12.130205,10.175614,0,0,22.095060,2.018872,4.037743,22.095060,1.227503,3.707764,...,0.0,8.426174,47.587636,252.208930,5.482803,941,16,68.0,67.0,4.666667

### Fingerprints

In [5]:
desc_fp_m = descriptors.get_fingerprint_df(data.SMILES,fp_type='m')
desc_fp_m

,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,...,m2039,m2040,m2041,m2042,m2043,m2044,m2045,m2046,m2047,m2048
CO,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C=NCCC(CCO)CCCCOC(=O)C=O,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CCC=C=NC#CCC=NCCC(CCO)CCCCOC(=O)C=O,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C#CCCCCOCCC=C=NC#CCC=NCCC(CCO)CCCCOC(=O)C=O,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
O=CC(=O)OCCCCC(CCO)CCN=CCC#CN=C=CCCOCCCCC1=CCCC=C1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CCCC(C)CCC1=C(C)C=C1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CCCSCC=CC(C)CN=O,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CCCCC=O,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CCCC=CCCC(C)CCCC=CCO,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CCC(C)CCCC=CC=CCOCCCC=O,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
desc_fp_ap = descriptors.get_fingerprint_df(data.SMILES,fp_type='ap')
desc_fp_ap

,ap1,ap2,ap3,ap4,ap5,ap6,ap7,ap8,ap9,ap10,...,ap2039,ap2040,ap2041,ap2042,ap2043,ap2044,ap2045,ap2046,ap2047,ap2048
CO,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C=NCCC(CCO)CCCCOC(=O)C=O,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CCC=C=NC#CCC=NCCC(CCO)CCCCOC(=O)C=O,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C#CCCCCOCCC=C=NC#CCC=NCCC(CCO)CCCCOC(=O)C=O,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
O=CC(=O)OCCCCC(CCO)CCN=CCC#CN=C=CCCOCCCCC1=CCCC=C1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CCCC(C)CCC1=C(C)C=C1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CCCSCC=CC(C)CN=O,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CCCCC=O,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CCCC=CCCC(C)CCCC=CCO,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CCC(C)CCCC=CC=CCOCCCC=O,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
desc_fp_tt = descriptors.get_fingerprint_df(data.SMILES,fp_type='tt')
desc_fp_tt

,tt1,tt2,tt3,tt4,tt5,tt6,tt7,tt8,tt9,tt10,...,tt2039,tt2040,tt2041,tt2042,tt2043,tt2044,tt2045,tt2046,tt2047,tt2048
CO,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C=NCCC(CCO)CCCCOC(=O)C=O,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CCC=C=NC#CCC=NCCC(CCO)CCCCOC(=O)C=O,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C#CCCCCOCCC=C=NC#CCC=NCCC(CCO)CCCCOC(=O)C=O,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
O=CC(=O)OCCCCC(CCO)CCN=CCC#CN=C=CCCOCCCCC1=CCCC=C1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CCCC(C)CCC1=C(C)C=C1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CCCSCC=CC(C)CN=O,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CCCCC=O,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CCCC=CCCC(C)CCCC=CCO,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CCC(C)CCCC=CC=CCOCCCC=O,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
desc_fp_rk = descriptors.get_fingerprint_df(data.SMILES,fp_type='rk')
desc_fp_rk

,rk1,rk2,rk3,rk4,rk5,rk6,rk7,rk8,rk9,rk10,...,rk2039,rk2040,rk2041,rk2042,rk2043,rk2044,rk2045,rk2046,rk2047,rk2048
CO,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C=NCCC(CCO)CCCCOC(=O)C=O,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
CCC=C=NC#CCC=NCCC(CCO)CCCCOC(=O)C=O,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
C#CCCCCOCCC=C=NC#CCC=NCCC(CCO)CCCCOC(=O)C=O,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
O=CC(=O)OCCCCC(CCO)CCN=CCC#CN=C=CCCOCCCCC1=CCCC=C1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CCCC(C)CCC1=C(C)C=C1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CCCSCC=CC(C)CN=O,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
CCCCC=O,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CCCC=CCCC(C)CCCC=CCO,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CCC(C)CCCC=CC=CCOCCCC=O,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
desc_fp_maccs = descriptors.get_fingerprint_df(data.SMILES,fp_type='mac')
desc_fp_maccs

,mac1,mac2,mac3,mac4,mac5,mac6,mac7,mac8,mac9,mac10,...,mac158,mac159,mac160,mac161,mac162,mac163,mac164,mac165,mac166,mac167
CO,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,1,0,0
C=NCCC(CCO)CCCCOC(=O)C=O,0,0,0,0,0,0,0,0,0,0,...,1,1,1,0,1,0,0,1,0,0
CCC=C=NC#CCC=NCCC(CCO)CCCCOC(=O)C=O,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,0,0
C#CCCCCOCCC=C=NC#CCC=NCCC(CCO)CCCCOC(=O)C=O,0,0,0,0,0,0,0,0,0,0,...,1,1,1,0,1,0,0,1,0,0
O=CC(=O)OCCCCC(CCO)CCN=CCC#CN=C=CCCOCCCCC1=CCCC=C1,0,0,0,0,0,0,0,0,0,0,...,1,1,1,0,1,0,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CCCC(C)CCC1=C(C)C=C1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
CCCSCC=CC(C)CN=O,0,0,0,0,0,0,0,0,0,0,...,0,1,0,1,1,0,0,1,0,0
CCCCC=O,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
CCCC=CCCC(C)CCCC=CCO,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,1,0,0
CCC(C)CCCC=CC=CCOCCCC=O,0,0,0,0,0,0,0,0,0,0,...,1,0,1,1,0,0,0,1,0,0

### Chemotypes

In [10]:
desc_chemotypes = descriptors.get_chemotypes(data.SMILES,n_jobs=-1)
desc_chemotypes

,Carbon,Carbanion,Carbocation,Carbon > 40% tot atoms,Carbon > 60% tot atoms,Carbon > 80% tot atoms,Aromatic Carbon,Aromatic Carbon > 10% tot atoms,Aromatic Carbon > 30% tot atoms,Aromatic Carbon > 50% tot atoms,...,O-Heterocycle (Aromatic),S-Heterocycle,S-Heterocycle (Aromatic),Zwitterion,H-Bond acceptors,H-Bond acceptors > 2,H-Bond acceptors > 5,H-Bond donors,H-Bond donors > 2,H-Bond donors > 5
CO,True,False,False,True,False,False,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False
C=NCCC(CCO)CCCCOC(=O)C=O,True,False,False,True,True,False,False,False,False,False,...,False,False,False,False,True,True,False,True,False,False
CCC=C=NC#CCC=NCCC(CCO)CCCCOC(=O)C=O,True,False,False,True,True,False,False,False,False,False,...,False,False,False,False,True,True,True,True,False,False
C#CCCCCOCCC=C=NC#CCC=NCCC(CCO)CCCCOC(=O)C=O,True,False,False,True,True,False,False,False,False,False,...,False,False,False,False,True,True,True,True,False,False
O=CC(=O)OCCCCC(CCO)CCN=CCC#CN=C=CCCOCCCCC1=CCCC=C1,True,False,False,True,True,True,False,False,False,False,...,False,False,False,False,True,True,True,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CCCC(C)CCC1=C(C)C=C1,True,False,False,True,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
CCCSCC=CC(C)CN=O,True,False,False,True,True,False,False,False,False,False,...,False,False,False,False,True,True,False,False,False,False
CCCCC=O,True,False,False,True,True,True,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
CCCC=CCCC(C)CCCC=CCO,True,False,False,True,True,True,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False
CCC(C)CCCC=CC=CCOCCCC=O,True,False,False,True,True,True,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False

In [11]:
desc_chemotypes_binary = 1*desc_chemotypes
desc_chemotypes_binary

,Carbon,Carbanion,Carbocation,Carbon > 40% tot atoms,Carbon > 60% tot atoms,Carbon > 80% tot atoms,Aromatic Carbon,Aromatic Carbon > 10% tot atoms,Aromatic Carbon > 30% tot atoms,Aromatic Carbon > 50% tot atoms,...,O-Heterocycle (Aromatic),S-Heterocycle,S-Heterocycle (Aromatic),Zwitterion,H-Bond acceptors,H-Bond acceptors > 2,H-Bond acceptors > 5,H-Bond donors,H-Bond donors > 2,H-Bond donors > 5
CO,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
C=NCCC(CCO)CCCCOC(=O)C=O,1,0,0,1,1,0,0,0,0,0,...,0,0,0,0,1,1,0,1,0,0
CCC=C=NC#CCC=NCCC(CCO)CCCCOC(=O)C=O,1,0,0,1,1,0,0,0,0,0,...,0,0,0,0,1,1,1,1,0,0
C#CCCCCOCCC=C=NC#CCC=NCCC(CCO)CCCCOC(=O)C=O,1,0,0,1,1,0,0,0,0,0,...,0,0,0,0,1,1,1,1,0,0
O=CC(=O)OCCCCC(CCO)CCN=CCC#CN=C=CCCOCCCCC1=CCCC=C1,1,0,0,1,1,1,0,0,0,0,...,0,0,0,0,1,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CCCC(C)CCC1=C(C)C=C1,1,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CCCSCC=CC(C)CN=O,1,0,0,1,1,0,0,0,0,0,...,0,0,0,0,1,1,0,0,0,0
CCCCC=O,1,0,0,1,1,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
CCCC=CCCC(C)CCCC=CCO,1,0,0,1,1,1,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
CCC(C)CCCC=CC=CCOCCCC=O,1,0,0,1,1,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

### Save molecular descriptors, fingerprints and chemotypes in a single file

In [12]:
dfs_to_excel('all_descriptors.xlsx',dfs=[desc_rdkit,
                                         desc_mordred_filtered,
                                         desc_fp_m,
                                         desc_fp_ap,
                                         desc_fp_tt,
                                         desc_fp_rk,
                                         desc_fp_maccs,
                                         desc_chemotypes_binary],
                                     sheet_names=['rdkit',
                                                  'mordred',
                                                  'fp_morgan',
                                                  'fp_atompair',
                                                  'fp_toptorsion',
                                                  'fp_rdkit',
                                                  'fp_maccs',
                                                  'chemotypes'])

### Check atomic descriptors for a given molecule

In [13]:
# atomic descriptors for the atom number 4 (index +1 as it's a 0-based index) in the molecule CCCO (propanol)
descriptors.get_atomicDesc('CCCO',3)

,SMILES,SMILES_H,SYMBOL,total_degree,total_valence,formal_charge,is_SP,is_SP2,is_SP3,tot_single_b,...,min_gasteiger_charge_neighbours,avg_gasteiger_charge_neighbours2,tot_gasteiger_charge_neighbours2,max_gasteiger_charge_neighbours2,min_gasteiger_charge_neighbours2,avg_gasteiger_charge_neighbours3,total_gasteiger_charge_neighbours3,max_gasteiger_charge_neighbours3,min_gasteiger_charge_neighbours3,average_eucl_dist_in_mol
CCCO,CCCO,[H]OC([H])([H])C([H])([H])C([H])([H])[H],O,2,2,0,0,0,1,1,...,0.042789,0.042789,0.042789,0.042789,0.042789,0.042789,0.042789,0.042789,0.042789,2.326693

In [14]:
# atomic descriptors for the nitrogen atom of nitrobutane
descriptors.get_atomicDesc('CCCC[N+](=O)[O-]',4)

,SMILES,SMILES_H,SYMBOL,total_degree,total_valence,formal_charge,is_SP,is_SP2,is_SP3,tot_single_b,...,min_gasteiger_charge_neighbours,avg_gasteiger_charge_neighbours2,tot_gasteiger_charge_neighbours2,max_gasteiger_charge_neighbours2,min_gasteiger_charge_neighbours2,avg_gasteiger_charge_neighbours3,total_gasteiger_charge_neighbours3,max_gasteiger_charge_neighbours3,min_gasteiger_charge_neighbours3,average_eucl_dist_in_mol
CCCC[N+](=O)[O-],CCCC[N+](=O)[O-],[H]C([H])([H])C([H])([H])C([H])([H])C([H])([H]...,N,3,4,1,0,1,0,2,...,-0.264549,-0.108563,-0.325689,0.203408,-0.264549,-0.108563,-0.325689,0.203408,-0.264549,3.073122

### Quantum chemical descriptors

In [15]:
mol = create_molecule('c1ccccc1CCCO',is_3d=True)
descriptors.get_EHT_descriptors(mol)

{'AtomicCharges': array([-0.34463776, -0.20701019,  0.07269296, -0.22915957, -0.30144556,
         0.42780534,  0.42540695,  0.1474089 ,  1.12137599, -1.11243708]),
 'Hamiltonian': array([[-2.14000000e+01, -0.00000000e+00, -0.00000000e+00, ...,
          3.30342147e-03, -3.85947647e-04, -1.45563368e-04],
        [-0.00000000e+00, -1.14000000e+01, -0.00000000e+00, ...,
          3.92689415e-03, -4.93958766e-04, -1.86300661e-04],
        [-0.00000000e+00, -0.00000000e+00, -1.14000000e+01, ...,
         -4.93958766e-04, -2.43310690e-04,  2.17660090e-05],
        ...,
        [-0.00000000e+00, -0.00000000e+00, -0.00000000e+00, ...,
         -1.48000000e+01, -0.00000000e+00, -0.00000000e+00],
        [-0.00000000e+00, -0.00000000e+00, -0.00000000e+00, ...,
         -0.00000000e+00, -1.48000000e+01, -0.00000000e+00],
        [-0.00000000e+00, -0.00000000e+00, -0.00000000e+00, ...,
         -0.00000000e+00, -0.00000000e+00, -1.48000000e+01]],
       shape=(40, 40)),
 'OrbitalEnergies': array([-34.02113492, -29.81562407, -27.22772635, -25.55218259,
        -24.90795735, -21.26983932, -18.89458952, -18.3468165 ,
        -16.70786237, -15.18561281, -15.09177808, -14.79809873,
        -14.43066452, -14.28365934, -13.81189423, -12.96819603,
        -12.80640706, -12.69649916, -12.36690778, -11.93679648,
        -11.72090919, -11.4764092 , -10.58939868,  -9.87794601,
         -9.75618075,  -9.23538046,  -8.42942476,  -8.26367901,
         -7.89079449,  -4.49096856,   4.53369055,   7.56504914,
         15.65023   ,  16.93280181,  23.92104593,  25.8910317 ,
         31.62800336,  42.76146151,  45.55617462,  66.20427576]),
 'OverlapMatrix': array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         -1.02394660e-04,  1.19630445e-05,  4.51196181e-06],
        [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00, ...,
         -1.69680852e-04,  2.13439276e-05,  8.05003997e-06],
        [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00, ...,
          2.13439276e-05,  1.05134398e-05, -9.40507899e-07],
        ...,
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  1.00000000e+00]],
       shape=(40, 40)),
 'ReducedChargeMatrix': array([[ 8.41058018e-06,  1.59282369e-01,  1.27065283e-02,
          2.26987372e-01,  7.01303210e-02,  5.54569840e-02,
          1.61186192e-01,  1.09251381e-01,  4.27884153e-02,
          2.77024657e-03,  1.08758759e-02,  6.46819782e-02,
          1.47927812e-01,  7.74241282e-02,  4.87042919e-02,
          1.97664141e-02,  2.67063256e-01,  1.04680239e-01,
          7.87301201e-02,  1.92734584e-01,  3.19161984e-01,
          3.77990760e-02,  1.05613118e-02,  1.09477231e-01,
          1.91219712e-02,  1.95209260e-01,  5.97745809e-02,
          1.99877811e-01,  4.51011306e-02,  1.67520341e-01,
          6.95696143e-03,  1.44195406e-02,  1.58265820e-01,
          7.10636264e-02,  1.09523412e-01,  8.21882182e-02,
          4.34365437e-02,  2.07212908e-01,  1.20863204e-01,
          1.69308148e-01],
        [-1.29416290e-08,  1.31436554e-01,  8.86341046e-02,
          2.26705237e-01,  4.83390336e-02,  4.65559571e-02,
          1.60729267e-01,  1.05121893e-01,  3.34296054e-02,
          2.69698134e-03,  4.74198906e-03,  4.15956190e-02,
          1.59680074e-01,  1.37502941e-01,  7.13848279e-02,
          6.00538261e-02,  2.29916540e-01,  1.08993971e-01,
          4.97599338e-02,  2.39159151e-01,  1.57067587e-01,
          1.70067884e-02,  7.14130491e-03,  1.01920532e-01,
          5.84152529e-02,  1.98297186e-01,  4.14356870e-02,
          2.20496528e-01,  9.89267256e-02,  1.48185732e-01,
          5.38013473e-03,  9.12985615e-03,  1.73550399e-01,
          5.20652130e-02,  1.02041802e-01,  1.02942479e-01,
          9.49381793e-02,  2.04647073e-01,  1.04161920e-01,
          1.55812125e-01],
        [ 4.70770309e-08,  1.24204465e-01,  1.64749945e-01,
          4.63427607e-02,  1.41199925e-01,  7.85846576e-02,
          1.72327239e-01,  8.67076525e-02,  1.71324020e-02,
          4.50224218e-04,  3.62875715e-03,  3.47229480e-02,
          1.59232184e-01,  1.58083429e-01,  2.58045925e-02,
          1.47199509e-01,  1.74097675e-03,  4.29921590e-01,
          1.26027067e-01,  1.31262390e-02,  3.24669106e-02,
          3.49512877e-02,  8.20421556e-02,  2.82877901e-01,
          1.03394828e-01,  6.75928290e-02,  3.30976124e-03,
          9.05993623e-04,  3.17209641e-01,  1.42766688e-01,
          4.80641200e-04,  4.28228721e-04,  1.76608565e-01,
          3.50584084e-03,  2.78662321e-01,  3.15744038e-02,
          6.75642348e-02,  8.24161184e-02,  2.03828849e-01,
          1.56226192e-01],
        [-7.59659389e-09,  1.31439068e-01,  8.85757407e-02,
          2.27029187e-01,  4.80468142e-02,  4.65168770e-02,
          1.60379689e-01,  1.05966545e-01,  3.28280783e-02,
          3.00999508e-03,  4.94619044e-03,  3.97748765e-02,
          1.56521086e-01,  1.46139094e-01,  6.59872218e-02,
          4.46820919e-02,  2.67221522e-01,  1.02947425e-01,
          3.60380642e-02,  1.98991209e-01,  2.07539013e-01,
          4.95133170e-03,  1.09947374e-02,  1.19239779e-01,
          3.59253121e-02,  1.98311527e-01,  6.20553206e-02,
          1.95861243e-01,  1.05255451e-01,  1.48173605e-01,
          5.44121624e-03,  8.95372143e-03,  1.74680244e-01,
          5.07530352e-02,  1.02956908e-01,  1.02334952e-01,
          9.49266765e-02,  2.04446552e-01,  1.04355767e-01,
          1.55802837e-01],
        [ 8.33433723e-06,  1.59290848e-01,  1.27060471e-02,
          2.26662446e-01,  7.04822511e-02,  5.56243681e-02,
          1.61364364e-01,  1.08804724e-01,  4.21763249e-02,
          3.80204242e-03,  1.12495323e-02,  6.06513154e-02,
          1.39434718e-01,  9.57116666e-02,  4.04877181e-02,
          4.90425437e-02,  2.29786947e-01,  1.01506898e-01,
          7.92038340e-02,  2.64569511e-01,  2.38156358e-01,
          5.85146173e-02,  2.44193344e-02,  4.74638394e-02,
          6.57156925e-02,  1.98307893e-01,  3.94453212e-02,
          2.24232248e-01,  4.03756156e-02,  1.67497796e-01,
          7.79911949e-03,  1.33470279e-02,  1.59632731e-01,
          6.99419467e-02,  1.08565949e-01,  8.34921950e-02,
          4.30811024e-02,  2.07414536e-01,  1.20733673e-01,
          1.69296570e-01],
        [ 1.09242404e-04,  2.11454719e-01,  1.09707207e-01,
          4.59153861e-02,  1.34400788e-01,  9.53522299e-02,
          1.74339007e-01,  8.45912724e-02,  9.45387771e-02,
          1.23582575e-02,  3.11477445e-02,  1.20676673e-01,
          1.41738305e-01,  5.75699545e-02,  1.37388163e-01,
          1.39791469e-01,  1.47117707e-03,  4.27496132e-02,
          1.10934834e-01,  7.44757967e-03,  3.24149438e-02,
          7.02577235e-03,  2.45070598e-02,  9.78558426e-03,
          1.93038940e-02,  6.96283951e-02,  6.58390552e-03,
          1.47255310e-03,  3.15385740e-01,  2.10119724e-01,
          9.63423185e-02,  1.23011580e-01,  1.55045087e-01,
          1.67595478e-01,  2.96722937e-01,  1.87682548e-02,
          1.53462131e-01,  9.39166924e-02,  2.60010684e-01,
          1.85214865e-01],
        [ 2.24480486e-03,  6.30263342e-02,  2.56527233e-01,
          3.48098805e-04,  5.57882472e-02,  2.18673536e-01,
          9.14202975e-03,  8.10954528e-02,  1.73817925e-01,
          1.28743060e-02,  4.22945662e-02,  7.58578038e-02,
          6.02212021e-02,  5.75586617e-02,  2.85348261e-01,
          1.15918988e-01,  4.29106765e-04,  4.88269642e-02,
          2.04817659e-01,  1.68854976e-02,  5.59983614e-03,
          2.30756797e-01,  2.73058239e-01,  1.09795494e-01,
          2.48778435e-01,  3.29886996e-03,  2.59261270e-01,
          5.12032469e-02,  5.05287578e-02,  9.26517532e-03,
          1.75364160e-01,  2.10830258e-01,  2.16112525e-03,
          1.24566779e-01,  1.43264677e-03,  1.23264422e-01,
          2.50247543e-01, -8.72319518e-05,  8.06257792e-02,
          8.35171951e-03],
        [ 1.56116055e-02,  1.65632407e-02,  2.02160176e-01,
          9.08258461e-06,  2.53022958e-01,  1.26811455e-01,
          4.85054625e-04,  9.44040597e-02,  1.74208531e-01,
          1.72224065e-02,  5.06820770e-02,  9.85525892e-02,
          1.59363076e-02,  7.37684407e-02,  2.18223279e-01,
          2.26048009e-01,  8.01267847e-04,  3.19578352e-02,
          2.68907839e-01,  3.52786304e-02,  5.64073017e-03,
          1.11998170e-01,  1.74930529e-01,  4.42984757e-02,
          2.47536238e-01,  2.37610417e-02,  3.58691278e-01,
          7.51386297e-02,  2.16395360e-02,  6.12147790e-03,
          2.35704050e-01,  7.54187783e-02,  4.83504507e-05,
          2.51769577e-01,  8.93632228e-05,  2.52331258e-01,
          1.89371557e-01,  3.22849444e-05,  4.84392051e-03,
         -2.00893953e-05],
        [ 1.85264215e-01,  1.18333398e-03,  4.42640968e-02,
          3.80454939e-07,  1.42238200e-01,  2.18339758e-01,
          3.41601334e-05,  1.30335106e-01,  1.42878197e-01,
          1.25568954e-01,  7.04550609e-02,  1.11679710e-01,
          7.39556787e-04,  6.56598012e-02,  2.46061895e-02,
          1.12004176e-01,  9.92550811e-04,  1.74223275e-02,
          2.05081316e-02,  2.38705734e-02,  1.26751547e-03,
          4.12511317e-01,  3.51985274e-01,  1.58567028e-01,
          1.79270854e-01,  4.21429171e-02,  1.55720135e-01,
          2.82246531e-02,  5.14304052e-03,  3.31315765e-04,
          3.97710879e-01,  3.93252697e-01,  6.89986624e-06,
          1.83650437e-01,  4.23866344e-06,  1.91642518e-01,
          5.99758840e-02,  8.03386470e-07,  5.40335103e-04,
          6.77907624e-06],
        [ 7.96753361e-01,  2.11906748e-03,  1.99689220e-02,
          5.01422986e-08,  3.63514606e-02,  5.80841774e-02,
          1.29972730e-05,  9.37219148e-02,  2.46201744e-01,
          8.19246587e-01,  7.69978207e-01,  3.51806487e-01,
          1.85687551e-02,  1.30581883e-01,  8.20654554e-02,
          8.54929734e-02,  5.76655530e-04,  1.09931371e-02,
          2.50725174e-02,  7.93702472e-03,  6.85120672e-04,
          8.44848428e-02,  4.03600535e-02,  1.65741352e-02,
          2.25375218e-02,  3.45008076e-03,  1.37227403e-02,
          2.58709312e-03,  4.34361298e-04,  1.81444387e-05,
          6.88205186e-02,  1.51208312e-01,  7.77180818e-07,
          2.50880678e-02,  4.21957744e-07,  1.14612984e-02,
          2.99614924e-03,  2.63051312e-07,  3.58681488e-05,
          8.53514818e-07]]),
 'ReducedOverlapPopulationMatrix': array([ 3.37996919e+00,  1.16293163e+00,  3.15632539e+00, -4.66370760e-02,
         1.18382205e+00,  2.81713671e+00, -1.02767017e-01, -6.31743522e-02,
         1.18711619e+00,  3.17871155e+00, -4.96443297e-02, -9.90261541e-02,
        -4.30040602e-02,  1.16386909e+00,  3.33385615e+00,  1.02405675e+00,
        -8.02250112e-02, -6.19371858e-02, -8.17928188e-02,  1.02604780e+00,
         2.28320595e+00, -4.97595231e-02, -2.91504863e-03,  9.27574386e-04,
        -2.59082335e-03, -4.82880325e-02,  8.25398479e-01,  2.68130455e+00,
        -8.85901247e-03, -5.01321130e-05,  5.47683772e-05,  2.41977952e-04,
        -1.49591712e-02, -6.93895884e-02,  1.08296236e+00,  2.95513898e+00,
         8.55362638e-06,  6.77855937e-06, -1.64244854e-06, -6.27010357e-06,
         1.89534378e-04, -4.33946337e-03, -4.21959903e-03,  8.64192705e-01,
         2.08756526e+00,  7.26396287e-06, -2.16250619e-07,  4.60413724e-08,
         4.84438699e-08, -5.82314913e-06,  1.58514509e-04, -1.49384324e-02,
        -5.92895686e-02,  7.26286863e-01,  6.78632765e+00]),
 'FermiEnergy': -11.720909118652344,
 'NumElectrons': 42,
 'NumOrbitals': 40,
 'TotalEnergy': -757.6823120117188}